name: restaurante_backend
description: A new Dart project.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.1.1
  shelf_router: ^1.0.0
  postgres: ^2.4.1
  shelf_cors_headers: ^0.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
